# Criando um Numpy Array

In [1]:
import numpy as np # esse np é um apelido ao numpy


In [4]:
#criando um numpy array 1 dimensão
arr = np.array([10,20,30,40,50,60])#a lista só alimentou o numpy array
print(arr)
print(type(arr))
print(arr.size)#tamanho do array
print(arr.ndim)#dimensão do array
print(arr.shape)#tamanho

mtz = np.array([[10,20],[30,40],[50,60]])#matriz
print(mtz)
print(mtz.size)
print(mtz.ndim)
print(mtz.shape)

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
6
1
(6,)
[[10 20]
 [30 40]
 [50 60]]
6
2
(3, 2)


# Funções pré-prontas para estruturarmos numpy arrays

In [7]:
#Ones
mtz = np.ones([5,5])
print(mtz)

#Zeros
arr = np.zeros(10)
print(arr)

#transfromando uma array uni dimension e two dimension(matriz)
print(arr.reshape(5,2))

#Arange(alcance do array)
mtz = np.arange(2, 21, 2)
print(mtz)
print(mtz.reshape(2, 5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


# Operações entre numpy arrays

In [11]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60,40, 20, 10, 5])
arr3 = arr1 + arr2

#Operações entre arrays
#somas de elementos de cada array de acordo com cada indice, no java a gente fazia um for e comparava se o indice do arr1 for igual ao do arr2 soma seus elementos
print(arr3)
print(arr1 - arr2)
print(arr1 * arr2)

#Concatenação de arrays
arr3 = np.concatenate([arr1, arr2])
print(arr3)

#Broadcasting - quando um escalar faz uma operação com um array
print(5 * arr3)

[70 60 50 50 55]
[-50 -20  10  30  45]
[600 800 600 400 250]
[10 20 30 40 50 60 40 20 10  5]
[ 50 100 150 200 250 300 200 100  50  25]


In [20]:
#estruturando uma matriz com contas
mtz = np.arange(10,96, 5)
mtz = mtz.reshape(3, 6)
print(mtz)

#Extraindo a soma da primeira coluna
print(mtz.sum(axis = 0)) #Eixo 0 = coluna, soma de todas as colunas
print(mtz.sum(axis = 0) [0]) #só da primeira coluna

#Extraindo a soma da segunda linha
print(mtz.sum(axis = 1)[1])

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
[120 135 150 165 180 195]
120
315


# Números aleatórios no numpy(módulo random)

In [29]:
#Platando a mesma semente aleatória, quando quer manipular o algoritmos de números aleatóris a partir do mesmo princípio que eles foram criados
np.random.seed(5)

arr = np.random.randint(1, 10, 10) # escolha 10  números aleatórios dentro de 1 a 10
print(arr)

#extraindo elementos únicos de um vetor, ordena os elementos
print(np.unique(arr))

#Contando elementos únicos
print(np.unique(arr, return_counts = True)) #retornou duas tuplas


[4 7 7 1 9 5 8 1 1 8]
[1 4 5 7 8 9]
(array([1, 4, 5, 7, 8, 9]), array([3, 1, 1, 2, 2, 1]))
