##Slicing no NumPy

In [1]:
import numpy as np

In [5]:
#criando a matriz
#palntando a mesma semente aleatória
np.random.seed(10)

#pedindo para criar uma matriz com nove números aleatórios dentro desse intervalo, depois restruturamos a matriz
mtz =  np.random.randint(1,99,9).reshape(3,3)
print(mtz)



[[10 16 65]
 [29 90 94]
 [30  9 74]]


In [7]:
#Extraindo apenas a segunda linha da matriz
print(mtz[1])
#Extraindo apenas a terceira coluna da matriz, os : pega todos os elementos
print(mtz[:, 2])
#Extraindo a matriz 2x2 no canto inferior direito da amtriz original
print(mtz[1:,1:])#está dizendo quero os elementos da fileira 1 e coluna 1 para a frente

[29 90 94]
[65 94 74]
[[90 94]
 [ 9 74]]


##Condicionais no Numpy

In [11]:
#mostre apenas os elementos menores que 70
#print(mtz<70) #fez esse condicional dentro de todos os elementos
#print(mtz[mtz<70])

#retorne apenas os números pares
print(mtz%2 == 0) #aqui retorna só a máscara
print(mtz[mtz%2 == 0])

[[ True  True False]
 [False  True  True]
 [ True False  True]]
[10 16 90 94 30 74]


##Análise de padrões textuais com NumPy

In [17]:
arr = np.array(["Inatel", 'CasaViva', 'ICC', 'CDG', 'eHealth', 'CSILab', 'RobotBulls', 'ProdLab', 'CRA', 'CRR'])
print(arr)

#padroniza todo mundo para maiusculo para não ter problema na hora de verificar se é minusculo ou maisculo
arr = np.char.upper(arr)

#submódulo do NumPy para tarbalhar com texto: char
#buscando qual texto aceita um padrão informado
print(np.char.find(arr, 'A')) # vai mostrar números indicando a posição da primeira vez que aparece 'a', vai mostrar -1 quando não atender o padrão
print(np.char.find(arr, 'A')>=0)

cond = np.char.find(arr, 'A')>=0
print(arr[cond])

['Inatel' 'CasaViva' 'ICC' 'CDG' 'eHealth' 'CSILab' 'RobotBulls' 'ProdLab'
 'CRA' 'CRR']
[ 2  1 -1 -1  3  4 -1  5  2 -1]
[ True  True False False  True  True False  True  True False]
['INATEL' 'CASAVIVA' 'EHEALTH' 'CSILAB' 'PRODLAB' 'CRA']


##Como importar Datasets no Numpy

In [18]:
#carregando o dataset e avisando que o delimitador que separa um dado do outro dentro do arquivo é o ';'
dataset = np.loadtxt('space.csv', delimiter = ';', dtype = 'str')
print(dataset)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


In [25]:
#extraindo as colunas do dataset
print(dataset[0,:]) #as colunas estão no top do dataset por isso colocou para mostrar a linha 0

#extraindo o nome das empresas
print(dataset[1:, 1])
print(np.unique(dataset[1:, 1], return_counts = True)) #extraindo e contando os elementos únicos

['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']
['SpaceX' 'CASC' 'SpaceX' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']
(array(['AEB', 'AMBA', 'ASI', 'Arianespace', "Arm??e de l'Air",
       'Blue Origin', 'Boeing', 'CASC', 'CASIC', 'CECLES', 'CNES',
       'Douglas', 'EER', 'ESA', 'Eurockot', 'ExPace', 'Exos',
       'General Dynamics', 'IAI', 'ILS', 'IRGC', 'ISA', 'ISAS', 'ISRO',
       'JAXA', 'KARI', 'KCST', 'Khrunichev', 'Kosmotras', 'Land Launch',
       'Landspace', 'Lockheed', 'MHI', 'MITT', 'Martin Marietta', 'NASA',
       'Northrop', 'OKB-586', 'OneSpace', 'RAE', 'RVSN USSR',
       'Rocket Lab', 'Roscosmos', 'SRC', 'Sandia', 'Sea Launch', 'SpaceX',
       'Starsem', 'ULA', 'US Air Force', 'US Navy', 'UT', 'VKS RF',
       'Virgin Orbit', 'Yuzhmash', 'i-Space'], dtype='<U84'), array([   3,    8,    9,  279,    4,   12,  136,  251,    5,    4,    8,
          1,    1,   13,   13,   10,    4,  251,   11,   46,    1,   13,
         30