In [2]:
import numpy as np

In [11]:
mtz = np.array([[5,2],[7,4],[9,15],[32,67],[1,9]])
print(mtz)
print(mtz.shape)#tamanho

tamanho = mtz.shape
multiplicacao = tamanho[0] * tamanho[1]

if(multiplicacao % 2 == 0):
  print("Pode se tornar unidimensional com um número par de elementos")
else:
  print("Pode se tornar unidimensional com um número ímpar de elementos")

[[ 5  2]
 [ 7  4]
 [ 9 15]
 [32 67]
 [ 1  9]]
(5, 2)
Pode se tornar unidimensional com um número par de elementos


In [21]:
np.random.seed(10) # para padronizar os números aleatórios
mtz = np.random.randint(1, 51,[4, 4])#matriz 4x4 formada por números de 0 até 50
print(mtz)

media_linhas = np.mean(mtz, axis=1)
media_colunas = np.mean(mtz, axis=0)
print("Média das linhas:", media_linhas)
print("Média das colunas:", media_colunas)

print(np.unique(mtz)) #mostra o números únicos do array

#mostra quantas vezes estes apareceram
numeros, quantidades = np.unique(mtz, return_counts=True)

for i in range(len(numeros)):
    if quantidades[i] == 2:
        print('Números que aparecem 2 vezes:',numeros[i])

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]
Média das linhas: [16.   33.75 34.5  23.75]
Média das colunas: [29.75 24.25 33.75 20.25]
[ 1  9 10 16 26 29 30 37 41 43 49 50]
Números que aparecem 2 vezes: 1
Números que aparecem 2 vezes: 10
Números que aparecem 2 vezes: 30
Números que aparecem 2 vezes: 50
